name: Build executables

on: 
  workflow_dispatch:
  
  release:
    types: [prerelease, published]

permissions:
  contents: read  
jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Check-out repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64'
          cache: pipenv
      - name: Install Dependencies
        run: |
          pip freeze
          curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
          pipenv install --dev
          pip freeze

      - name: Build Executable
        run: pipenv run python -m nuitka diary.py --include-data-files=template.txt=template.txt --output-dir=build --standalone --assume-yes-for-downloads

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }} Build
          path: |
            build/diary.dist/**
